services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: auth-bridge-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=auth_bridge_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourPassword123!
      - LDAP_URLS=ldap://ldap-server:389
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_USERNAME=admin
      - LDAP_PASSWORD=admin123
    depends_on:
      - db
      - ldap-server

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  ldap-server:
    image: osixia/openldap:latest
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin123"
    ports:
      - "389:389"
      - "636:636"
